<a href="https://colab.research.google.com/github/chi-yan/notebooks/blob/master/Sarcasm_Model_Trainer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [2]:
!pip install --upgrade tensorflow_hub

import tensorflow_hub as hub

In [3]:
!curl https://raw.githubusercontent.com/rishabhmisra/News-Headlines-Dataset-For-Sarcasm-Detection/master/Sarcasm_Headlines_Dataset.json > dataset.json

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5915k  100 5915k    0     0  16.7M      0 --:--:-- --:--:-- --:--:-- 16.7M


In [4]:
import json

f = open('dataset.json',)
data = []
x = [] #sentences
y = [] #labels
with open('dataset.json') as f:
    for line in f:
        #data.append(json.loads(line))
        x.append(json.loads(line)['headline'])
        y.append(json.loads(line)['is_sarcastic'])

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.10, random_state=42)

In [7]:
 embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

In [9]:
x_train_embeddings = embed(x_train)

In [11]:
#print(x_train_embeddings.shape)
print(len(y_train))

25757


In [12]:
print(x_train_embeddings.shape)

(25757, 512)


In [13]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train_embeddings, y_train)

LogisticRegression()

In [14]:
logreg.intercept_

array([-0.81340813])

In [15]:
print('Accuracy of Logistic regression classifier on train set: {:.4f}'
     .format(logreg.score(x_train_embeddings, y_train)))   #(true P + true N) / (EVERYTHING)

Accuracy of Logistic regression classifier on train set: 0.8055


In [16]:
x_test_embeddings = embed(x_test)

In [ ]:
print('Accuracy of Logistic regression classifier on test set: {:.4f}'
     .format(logreg.score(x_test_embeddings, y_test)))   #(true P + true N) / (EVERYTHING)

Accuracy of Logistic regression classifier on test set: 0.8075


In [ ]:
!pip install xgboost

In [ ]:
print(x_train_embeddings.shape)

(25757, 512)


In [ ]:
from xgboost import XGBClassifier
XGB = XGBClassifier()
XGB.fit(x_train_embeddings, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
print('Accuracy of Logistic regression classifier on train set: {:.4f}'
     .format(XGB.score(x_train_embeddings, y_train)))   #(true P + true N) / (EVERYTHING)

Accuracy of Logistic regression classifier on train set: 0.8074


In [25]:
x_test = ['tennis superstars lands a new job!',
          'education leads to a better life',
          'thirtysomething scientists unveil doomsday clock of hair loss',
          'ebola found in usa']

In [26]:
x_test_embeddings = embed(x_test)

In [27]:
logreg.predict(x_test_embeddings)

array([1, 0, 1, 0])

In [28]:
logreg.predict_proba(x_test_embeddings)

array([[0.45010703, 0.54989297],
       [0.92412281, 0.07587719],
       [0.0757196 , 0.9242804 ],
       [0.58100681, 0.41899319]])

In [ ]:
x_train

['the 30 most wtf moments of the 2014-2015 nba season',
 'peta condemns bbc for trapping thousands of endangered animals inside tv screens',
 'art object purchased at office depot',
 'mom tucks handwritten guide on how to use netflix into kitchen drawer',
 'this rescue pit bull made his bed every day while waiting to be adopted',
 'equifax says another 2.4 million customers hit by data breach in 2017',
 'watch: how belgium became a hotbed for terrorism',
 "trump warns china not to underestimate his willingness to sacrifice every american's well-being",
 "nation's deans meet to discuss problem of college girls going wild",
 'newly engaged couple receives incredible outpouring of insincerity from family, friends',
 'softball team unsure of how to console jackass captain who just struck out',
 'the republican plan for higher education: less red tape and less money',
 'moving forward into 2017: four resolutions if you are grieving',
 'zoo animals roam free after flooding in tbilisi',
 'sen

In [ ]:
!head dataset.json

{"is_sarcastic": 1, "headline": "thirtysomething scientists unveil doomsday clock of hair loss", "article_link": "https://www.theonion.com/thirtysomething-scientists-unveil-doomsday-clock-of-hai-1819586205"}
{"is_sarcastic": 0, "headline": "dem rep. totally nails why congress is falling short on gender, racial equality", "article_link": "https://www.huffingtonpost.com/entry/donna-edwards-inequality_us_57455f7fe4b055bb1170b207"}
{"is_sarcastic": 0, "headline": "eat your veggies: 9 deliciously different recipes", "article_link": "https://www.huffingtonpost.com/entry/eat-your-veggies-9-delici_b_8899742.html"}
{"is_sarcastic": 1, "headline": "inclement weather prevents liar from getting to work", "article_link": "https://local.theonion.com/inclement-weather-prevents-liar-from-getting-to-work-1819576031"}
{"is_sarcastic": 1, "headline": "mother comes pretty close to using word 'streaming' correctly", "article_link": "https://www.theonion.com/mother-comes-pretty-close-to-using-word-streaming